[mongodb]
mongodb.viswak.shop


[catalogue]
catalogue.viswak.shop


[redis]
redis.viswak.shop

[user]
user.viswak.shop

[cart]
cart.viswak.shop

[frontend]
viswak.shop

[shipping]
shipping.viswak.shop


[mysql]
mysql.viswak.shop


[rabbitmq] 
rabbitmq.viswak.shop

[payment]
payment.viswak.shop

[dispatch]
dispatch.viswak.shop

[local]
localhost

