[mongodb]
mongodb.viswak.shop


[catalogue]
catalogue.viswak.shop
172.31.30.192

[redis]
redis.viswak.shop

[user]
user.viswak.shop

[cart]
cart.viswak.shop

[frontend]
viswak.shop

[shipping]
shipping.viswak.shop


[mysql]
mysql.viswak.shop


[rabbitmq] 
rabbitmq.viswak.shop

[payment]
payment.viswak.shop

[dispatch]
dispatch.viswak.shop

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321